Filename: /home/bryan/Desktop/Utilities/Python/RevPie/AutoRevPie/Testing/logs.txt


 - - - Logs (2019-06-06 21:28.15) - - - 


2019-06-06 21:28:29.419008 
-------------------- 


switchTabs: Error while switching tabs, closing...

Message: Failed to decode response from marionette

Traceback (most recent call last):
  File "/home/bryan/Desktop/Utilities/Python/RevPie/AutoRevPie/Testing/AutomateRevPie/InitBrowser.py", line 64, in switchToTab
    browser.switch_to.window(browser.window_handles[tab])
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 724, in window_handles
    return self.execute(Command.W3C_GET_WINDOW_HANDLES)['value']
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette


2019-06-06 21:28:29.433496 
-------------------- 

checkBrowser: Error, closing...

Message: Tried to run command without establishing a connection

Traceback (most recent call last):
  File "/home/bryan/Desktop/Utilities/Python/RevPie/AutoRevPie/Testing/AutomateRevPie/InitBrowser.py", line 78, in checkBrowser
    browser.title
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in title
    resp = self.execute(Command.GET_TITLE)
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bryan/anaconda3/envs/environment_2/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection


